
extern gboolean GdmUseCirclesInEntry;
extern gboolean GdmShowGnomeChooserSession;
extern gboolean GdmShowGnomeFailsafeSession;
extern gboolean GdmShowXtermFailsafeSession;
extern gboolean GdmShowLastSession;
extern gboolean GdmSystemMenu;
extern gboolean GdmConfigAvailable;
extern gchar *GdmHalt;
extern gchar *GdmReboot;
extern gchar *GdmSuspend;
extern gchar *GdmConfigurator;
extern gchar *GdmSessionDir;
extern gchar *GdmDefaultLocale;
extern gchar *GdmLocaleFile;
extern gboolean GdmTimedLoginEnable;
extern gboolean GdmUse24Clock;
extern gchar *GdmTimedLogin;
extern gint GdmTimedLoginDelay;
