#define N_(x) x
#define _(x) x

static Language languages [] = {
	{ N_("Catalan"), "ca_ES" },
	{ N_("Chinese (simplified)"), "zh_CN" },
	{ N_("Chinese (traditional)"), "zh_TW" },
	{ N_("Croatian"), "hr_HR" },
	{ N_("Czech"), "cs_CZ" },
	{ N_("Danish"), "da_DK" },
	{ N_("Dutch"), "nl_NL" },
	{ N_("English"), "en" },
	{ N_("American English"), "en_US" },
	{ N_("British English"), "en_GB" },
	{ N_("Finnish"), "fi_FI" },
	{ N_("French"), "fr_FR" },
	{ N_("Galician"), "gl_ES" },
	{ N_("German"), "de_DE" },
	{ N_("Greek"), "el_GR" },
	{ N_("Hebrew"), "iw_IL" },
	{ N_("Hungarian"), "hu_HU" },
	{ N_("Icelandic"), "is_IS" },
	{ N_("Italian"), "it_IT" },
	{ N_("Japanese"), "ja_JP" },
	{ N_("Korean"), "ko_KR" },
	{ N_("Lithuanian"), "lt_LT" },
	{ N_("Norwegian (bokmal)"), "no_NO" },
	{ N_("Norwegian (nynorsk)"), "nn_NO" },
	{ N_("Polish"), "pl_PL" },
	{ N_("Portuguese"), "pt_PT" },
	{ N_("Brazilian Portuguese"), "pt_BR" },
	{ N_("Romanian"), "ro_RO" },
	{ N_("Russian"), "ru_RU" },
	{ N_("Slovak"), "sk_SK" },
	{ N_("Slovenian"), "sl_SI" },
	{ N_("Spanish"), "es_ES" },
	{ N_("Swedish"), "sv_SE" },
	{ N_("Turkish"), "tr_TR" },
	{ NULL, NULL }
};
