/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("GDM Host Chooser");
gchar *s = N_("Open a session to the selected host");
gchar *s = N_("Connect");
gchar *s = N_("Probe the network");
gchar *s = N_("Rescan");
gchar *s = N_("How to use this application");
gchar *s = N_("Help");
gchar *s = N_("Exit the application");
gchar *s = N_("Quit");
gchar *s = N_(" ");
gchar *s = N_("Most recently queried hosts");
gchar *s = N_("The main area of this application shows the hosts on the local\n"
              "network that have \"XDMCP\" enabled. This allows users to login\n"
              "remotely to other machines as if they were logged on using the\n"
              "console.\n"
              "\n"
              "You can rescan the network for new hosts by clicking 'rescan'.\n"
              "When you have selected a host click \"Connect\" to open a session\n"
              "to that machine.");
gchar *s = N_("Information");
