/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("GDM Setup");
gchar *s = N_("L_ocal: ");
gchar *s = N_("_Remote: ");
gchar *s = N_("Standard greeter");
gchar *s = N_("Graphical greeter");
gchar *s = N_("Standard greeter");
gchar *s = N_("Graphical greeter");
gchar *s = N_("Always use 24 hour cloc_k format");
gchar *s = N_("Greeter");
gchar *s = N_("_Login a user automatically on first bootup");
gchar *s = N_("_Automatic login username:");
gchar *s = N_("*");
gchar *s = N_("Automatic login");
gchar *s = N_("Login a user automa_tically after a specified number of seconds");
gchar *s = N_("Timed login us_ername:");
gchar *s = N_("_Seconds before login:");
gchar *s = N_("*");
gchar *s = N_("Timed login");
gchar *s = N_("General");
gchar *s = N_("*");
gchar *s = N_("_Welcome string: ");
gchar *s = N_("Welcome string: ");
gchar *s = N_("*");
gchar *s = N_("Logo");
gchar *s = N_("Show choosable user images (_face browser)");
gchar *s = N_("Miscellaneous");
gchar *s = N_("_No background");
gchar *s = N_("_Image");
gchar *s = N_("Co_lor");
gchar *s = N_("_Scale background image to fit");
gchar *s = N_("*");
gchar *s = N_("_Only color on remote displays");
gchar *s = N_("_Background color: ");
gchar *s = N_("Pick a color");
gchar *s = N_("Background");
gchar *s = N_("Standard greeter");
gchar *s = N_("<b>Preview:</b>");
gchar *s = N_("No screenshot available");
gchar *s = N_("<b>Description:</b>");
gchar *s = N_("<b>Author:</b>");
gchar *s = N_("description\n"
              "widget");
gchar *s = N_("author");
gchar *s = N_("copyright");
gchar *s = N_("_Install new theme");
gchar *s = N_("Graphical greeter");
gchar *s = N_("Allow _root to login with GDM");
gchar *s = N_("Allow root to login r_emotely with GDM");
gchar *s = N_("Allow remote _timed logins");
gchar *s = N_("Show _system menu");
gchar *s = N_("Allow c_onfiguration from the login screen");
gchar *s = N_("Retry _delay (seconds) :");
gchar *s = N_("Options");
gchar *s = N_("Security");
gchar *s = N_("No XDMCP support in the binary.  To enable XDMCP support you must recompile GDM with the XDMCP libraries.");
gchar *s = N_("Honour _indirect requests");
gchar *s = N_("Listen on UDP port: ");
gchar *s = N_("Maximum pending requests:");
gchar *s = N_("Max pending indirect requests:");
gchar *s = N_("Maximum remote sessions:");
gchar *s = N_("Maximum wait time:");
gchar *s = N_("Maximum indirect wait time:");
gchar *s = N_("Displays per host:");
gchar *s = N_("Ping interval (minutes):");
gchar *s = N_("Enable _XDMCP");
gchar *s = N_("XDMCP");
