/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("GDM Setup");
gchar *s = N_("Local: ");
gchar *s = N_("Remote: ");
gchar *s = N_("Standard greeter");
gchar *s = N_("Graphical greeter");
gchar *s = N_("Standard greeter");
gchar *s = N_("Graphical greeter");
gchar *s = N_("Greeter");
gchar *s = N_("Login a user automatically on first bootup");
gchar *s = N_("Automatic login username:");
gchar *s = N_("*");
gchar *s = N_("Automatic login");
gchar *s = N_("Login a user automatically after a specified number of seconds");
gchar *s = N_("Timed login username:");
gchar *s = N_("Seconds before login:");
gchar *s = N_("*");
gchar *s = N_("Timed login");
gchar *s = N_("General");
gchar *s = N_("Standard greeter");
gchar *s = N_("Graphical greeter");
gchar *s = N_("Allow root to login with GDM");
gchar *s = N_("Allow root to login remotely with GDM");
gchar *s = N_("Allow remote timed logins");
gchar *s = N_("Retry delay (seconds) :");
gchar *s = N_("Options");
gchar *s = N_("Security");
gchar *s = N_("No XDMCP support in the binary.  To enable XDMCP support you must recompile GDM with the XDMCP libraries.");
gchar *s = N_("Enable XDMCP");
gchar *s = N_("Honour indirect requests");
gchar *s = N_("Listen on UDP port: ");
gchar *s = N_("Maximum pending requests:");
gchar *s = N_("Max pending indirect requests:");
gchar *s = N_("Maximum remote sessions:");
gchar *s = N_("Maximum wait time:");
gchar *s = N_("Maximum indirect wait time:");
gchar *s = N_("Displays per host:");
gchar *s = N_("Ping interval (minutes):");
gchar *s = N_("Connection Settings");
gchar *s = N_("XDMCP");
