=head1 NAME

gdmchooser - GNOME Display Manager host chooser window

=head1 SYNOPSIS

gdmchooser

=head1 DESCRIPTION

B<gdmchooser> is invoked by gdm(8). It displays a list of hosts that
are candidates for logging into via a gdm(8) daemon or compatible,
such as xdm(1x) or wdm(1x).

=head1 SEE ALSO

gdm(8)

=head1 AUTHOR

Martin Kasper Petersen <mkp@SunSITE.auc.dk>

This manual page written by Steve Haslam <araqnid@debian.org> for
Debian GNU/Linux.

=cut
