=head1 NAME

gdmlogin - GNOME Display Manager greeting window

=head1 SYNOPSIS

gdmlogin

=head1 DESCRIPTION

B<gdmlogin> is invoked by gdm(8). It displays a GNOME login window
and obtains a login/password combination from the user. This is then
sent to the controlling B<gdm> process for verification.

=head1 SEE ALSO

gdm(8)

=head1 AUTHOR

Martin Kasper Petersen <mkp@SunSITE.auc.dk>

This manual page written by Steve Haslam <araqnid@debian.org> for
Debian GNU/Linux. Updated by Raphaël Hertzog <hertzog@debian.org>.
Updated by Ryan Murray <rmurray@debian.org>.

=cut
